import type { Metadata } from "next"

import { RootProvider } from "@partials/providers/RootProvider"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

import "@styles/globals.css"

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' className=''>
            <body>
                <RootProvider>{children}</RootProvider>
            </body>
        </html>
    )
}
