import type { Metadata } from "next"

import { RootProvider } from "@partials/providers/RootProvider"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

import { Maven } from "@core/configs/fonts/fonts.config"

import "@styles/globals.css"

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${Maven.variable} bg-khaki`}>
                <RootProvider>{children}</RootProvider>
            </body>
        </html>
    )
}
